version: 0.0
os: linux

files:
  - source: /
    destination: /home/DeployTemp

permissions:
  - object: start.sh
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root
